// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using divar.DAL;

#nullable disable

namespace divar.Migrations
{
    [DbContext(typeof(DivarDataContext))]
    [Migration("20240929115720_Experts")]
    partial class Experts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("divar.DAL.Models.Expert", b =>
                {
                    b.Property<int>("ExpertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("ExpertId");

                    b.ToTable("Experts");
                });

            modelBuilder.Entity("divar.DAL.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BookTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpertId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpertOption")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostToken")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReviewStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExpertId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("divar.DAL.Models.Reservation", b =>
                {
                    b.HasOne("divar.DAL.Models.Expert", "Expert")
                        .WithMany("Reservations")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expert");
                });

            modelBuilder.Entity("divar.DAL.Models.Expert", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
